apiVersion: v1
kind: Service
metadata:
  name: gymmatrix-ecr-backend-service
spec:
  type: LoadBalancer
  selector:
    app: gymmatrix-ecr-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080